### ISSUE TITLE
 AccountKit SDK was not initialized. Call AccountKit.init first.

### ISSUE THREAD

**Issue by raviranjan528** [rafael-iop/ng2-account-kit#1]
AccountKit.init({
      appId: 'myappid',
      state:"{{csrf}}",
      version: 'v1.0'
    })
but it is giving same error

**Comment by rafael-iop** [comment]
Can you provide a plunker version of the problem?

Where are you calling `AccountKit.init`?

Are you importing facebook account kit `sdk.js` in your `index.html`?

**Comment by raviranjan528** [comment]
i m calling AccountKit.init  app.component.ts.
and  yes i m importing sdk.js in index,html

**Comment by raviranjan528** [comment]
from where to take csrf code

**Comment by raviranjan528** [comment]
Thanks for rply ..its done
